config/routes.rb
Dauth::Application.routes.draw do
  resources :assignments


  resources :roles


  authenticated :user do
    root :to => "home#index"
  end

  resources :articles do
    resources :comments, only: [ :edit, :create, :update, :destroy ]
  end
  
  root :to => "home#index"
  
  devise_for :users
  resources :users, only: [ :index, :show ]
  
  devise_scope :user do
    delete "users/sign_out", :to => "devise/sessions#destroy"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_name, :content, :site_url,
    :user, :article

  belongs_to :user
  belongs_to :article
  
  validates :author_name, presence: true
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  filter_resource_access
  
  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @article = Article.find(params[:article_id])
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_url(@comment.article_id), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to article_url(@comment.article_id), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to article_url(article) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_area :content, :class => 'span6', :style => "height: 120px", :placeholder => "Add your comment here." %>
  </p>
  <p>
    <%= f.text_field :site_url, :class => 'span4', :placeholder => "URL of your website" %>
  </p>
  <p>
    <%= f.text_field :author_name, :class => 'span3', :placeholder => "Your name" %>
  </p>
  <p class="actions">
    <%= f.submit :class => "btn btn-warning" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_path(@article) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @comment.article %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Author name:</b>
  <%= @comment.author_name %>
</p>

<p>
  <b>Site url:</b>
  <%= @comment.site_url %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>