config/routes.rb
Dauth::Application.routes.draw do
  resources :assignments


  resources :roles


  authenticated :user do
    root :to => "home#index"
  end

  resources :articles do
    resources :comments, only: [ :edit, :create, :update, :destroy ]
  end
  
  root :to => "home#index"
  
  devise_for :users
  resources :users, only: [ :index, :show ]
  
  devise_scope :user do
    delete "users/sign_out", :to => "devise/sessions#destroy"
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author_name, :content, :name,
    :user, :comments
  
  belongs_to :user
  has_many :comments
  
  validates :name, presence: true
  validates :content, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  filter_resource_access
  
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article = @article

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <fieldset>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.text_field :name, :class => 'span6', :placeholder => "Add the title here" %>
    </p>
    <p>
      <%= f.text_area :content, :class => 'span6', :style => "height: 120px", :placeholder => "Enter the content here" %>
    </p>
    <p>
      <%= f.text_field :author_name, :class => 'span3', :placeholder => "What's your name?" %>
    </p>
    <p class="actions">
      <%= f.submit :class => "btn btn-warning" %>
    </p>
  </fieldset>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<table class="table table-bordered table-striped">
  <caption>
    <% if permitted_to? :new, Article.new %>
      <span class="pull-right"><%= link_to 'New Article', new_article_path, :class => 'btn btn-warning' %></span>
    <% end %>
    Articles
  </caption>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Author name</th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.name, article %></td>
    <td><%= truncate(article.content, length: 60) %></td>
    <td><%= article.author_name %></td>
    <td>
      <% if permitted_to? :edit, article %>
        <%= link_to 'Edit', edit_article_path(article), :class => 'btn btn-warning' %>
      <% end %>
      <% if permitted_to? :destroy, article %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p class=pull-right>
  <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-warning' %>
  <%= link_to 'Back', articles_path, :class => 'btn btn-info' %>
</p>

<h2><%= @article.name %></h2>

<p class="muted">
  by <%= @article.author_name %>
</p>

<p>
  <%= @article.content %>
</p>


<h3><%= pluralize(@article.comments.size, 'comment') %></h3>

<% unless @article.comments.empty? %>
  <% for comment in @article.comments %>
    <div class="comment">
      <p class="pull-right">
        <% if permitted_to? :edit, comment %>
          <%= link_to "Edit", edit_article_comment_path( @article, comment ), :class => 'btn-small btn-warning' %>
        <% end %>
        <% if permitted_to? :destroy, comment %>
          <%= link_to "Destroy", [ @article, comment ], :method => :delete, :confirm => "Are you sure?", :class => 'btn-small btn-danger' %>
        <% end %>
      </p>
    
      <p>
        On <strong class="text-success"><%= comment.created_at.strftime('%A, %d %b %Y at %H:%M %P') %></strong>
        <%= link_to_unless comment.site_url.blank?, comment.author_name, comment.site_url %> said:
      </p>
    
      <p class="content"><%= comment.content %></p>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render :partial => 'comments/form' %>